### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by x734545751k** [nswish/jQuery.AutoComplete#2]
I use the situation is this: a table, a table row using jQuery dynamic clone, I now clone out of the line of the automatic completion function cannot be used.Pop complete box is the original line by clone.

**Comment by nswish** [comment]
Since jQuery.clone method can't really clone everything of the object,  you'd better do a little more working.
Follow the [jsfiddle example url: http://jsfiddle.net/asfbv/3/](http://jsfiddle.net/asfbv/3/)  and this will help you.
