### ISSUE TITLE
希望增加一个规定最少输入字符数再请求服务器的特性

### ISSUE THREAD

**Issue by PandaFang** [nswish/jQuery.AutoComplete#3]
首先谢谢您贡献的插件！我在项目中用到了。
我以url 作为数据源，但数据有一个共性，开头3个字符是相同。
我知道，并不一定要一定要输入开头的字符进行匹配， 但仍希望能规定最少输入多少字符后再发出请求。
希望您能增加这个特性。再次感谢！

**Comment by nswish** [comment]
我脑子里有2种实现这个特性的备选方案。
1. 增加一个option属性，类型是数值，名字或许是'minLengthOfWordBeforeSearch'。当给这个属性赋值为3后，控件会在探知搜索字符串的长度大等于3时，发起search动作。
2. 增加一个option属性，类型是事件，名字或许是'beforeSearchHandler'。当给这个属性赋值为回调函数后，控件会在探知每次输入之后发起search动作之前，调用这个函数。如果这个函数返回false，则取消之后search动作，否则仍旧做search动作。

我喜欢第二个方案，因为更加通用，虽然它不如第一个方案来得直接。下一个版本我考虑加入的特性是第二个方案。你看如何？

**Comment by PandaFang** [comment]
我完完全全是个web新手啦，javascript jquery 边学边用中。搜索到的一些博客中讲的同类型插件貌似都是采用第一种，minChars 什么的。 不过第 2 个方案听起来不错，我能拿到已输入字符数，再通过返回值来决定是否开始search，此外能灵活应对其他更多处理，虽然还没想到要干些什么。
so 我也选方案 2

**Comment by nswish** [comment]
完成了！ 
详见： http://work.jiani.info/jQuery.AutoComplete/doc/index.html#beforeLoadDataHandler
