### ISSUE TITLE
请问Ajax返回的如果是json类型数据该怎么解析

### ISSUE THREAD

**Issue by woshihoujinxin** [nswish/jQuery.AutoComplete#5]
所谓的json是key：value形式，而不是向test下data.json中的
["One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine", "Ten", "Eleven", "Twelve"]，这是个数组啊？

**Comment by nswish** [comment]
可以使用这样的数据形式，[{'value':'One', 'label':'One'}, {'value':'Two', 'label':'Two'}]。其中，label对应下拉列表中可见的标签内容，value用以存放看不见的实际的数值。

另外，什么是json，可以去看看JSON的发明者的主页: http://www.json.org/
